import React, { useState, useEffect } from 'react';
import { getSecurityScoreColor, getPhishingRiskMessage } from '../utils/SecurityAPI';
import { jsPDF } from 'jspdf';
import '../styles/SecurityReport.css';

/**
 * Renders a security report for a scanned URL
 * @param {Object} props
 * @param {Object} props.securityReport - The security report data
 * @param {Function} props.onBack - Function to go back to scanning
 */
const SecurityReport = ({ securityReport, onBack }) => {
  const [showDetails, setShowDetails] = useState(false);
  const [isEmailing, setIsEmailing] = useState(false);
  const [email, setEmail] = useState('');
  const [emailSent, setEmailSent] = useState(false);
  
  useEffect(() => {
    if (securityReport) {
      console.log('Security report received in component:', JSON.stringify(securityReport, null, 2));
      console.log('Status:', securityReport.status);
      console.log('Is Safe:', securityReport.is_safe);
      console.log('Security Score:', securityReport.security_score);
      console.log('Summary:', securityReport.summary || 'No summary provided');
      console.log('Verdict Text:', getVerdictText(securityReport.status));
      console.log('Status Class:', getStatusClass());
    }
  }, [securityReport]);
  
  if (!securityReport) {
    return <div className="security-report error">No security report available</div>;
  }
  
  // Format date for better display
  const formatDate = (timestamp) => {
    if (!timestamp) return 'Unknown';
    return new Date(timestamp).toLocaleString();
  };
  
  // Handle downloading the report as PDF
  const downloadPDF = async () => {
    try {
      // Dynamically import html2canvas to reduce initial bundle size
      const html2canvas = (await import('html2canvas')).default;
      
      // Get the security report element
      const element = document.querySelector('.security-report');
      if (!element) {
        console.error('Security report element not found');
        return;
      }
      
      console.log('Creating PDF from element:', element);
      
      // Create canvas from DOM element
      const canvas = await html2canvas(element, {
        scale: 2,
        logging: false,
        useCORS: true,
        allowTaint: true,
      });
      
      // Get image data from canvas
      const imgData = canvas.toDataURL('image/png');
      
      // Create PDF document
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });
      
      // Calculate dimensions
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      // Add the image to the PDF
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      
      // Generate a filename with today's date
      const dateStr = new Date().toISOString().slice(0, 10);
      const statusLabel = securityReport.status || 'scan';
      const filename = `qr-security-report-${statusLabel}-${dateStr}.pdf`;
      
      // Save the PDF
      pdf.save(filename);
      console.log('PDF saved successfully as:', filename);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };
  
  // Handle email form submission
  const handleEmailSubmit = (e) => {
    e.preventDefault();
    
    if (!email || !email.trim()) return;
    
    try {
      // Generate email content
      const statusLabel = securityReport.status ? 
        securityReport.status.toUpperCase() : 
        (securityReport.is_safe ? 'SAFE' : 'UNKNOWN');
      
      // Create email subject
      const subject = `QR Scan Security Report [${statusLabel}]`;
      
      // Create email body
      const body = `
QR Code Security Report
-----------------------
Date: ${formatDate(securityReport.timestamp || new Date())}

URL: ${securityReport.url || 'Unknown URL'}
Security Status: ${getVerdictText(securityReport.status)}
Security Score: ${Math.round(securityReport.security_score || 0)}/100
HTTPS: ${securityReport.isHttps ? 'Yes' : 'No'}

Risk Assessment:
${securityReport.summary || getPhishingRiskMessage(securityReport)}

${securityReport.stats ? `
Detection Statistics:
- Malicious: ${securityReport.stats.malicious || 0}
- Suspicious: ${securityReport.stats.suspicious || 0}
- Harmless: ${securityReport.stats.harmless || 0}
- Undetected: ${securityReport.stats.undetected || 0}
` : ''}

-----------------------
Generated by Secure QR Scanner
      `.trim();
      
      // Create and open the mailto URL
      const mailtoUrl = `mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
      window.location.href = mailtoUrl;
      
      // Show success message
      setEmailSent(true);
      setTimeout(() => {
        setIsEmailing(false);
        setEmailSent(false);
        setEmail('');
      }, 2000);
    } catch (error) {
      console.error('Error sending email:', error);
      alert('Failed to open email client. Please try again.');
    }
  };
  
  // Helper to get status class
  const getStatusClass = () => {
    if (!securityReport) return 'unknown';
    if (securityReport.status === 'malicious') return 'unsafe';
    if (securityReport.status === 'suspicious') return 'warning';
    if (securityReport.status === 'safe') return 'safe';
    if (securityReport.is_safe) return 'safe';
    return 'unknown';
  };
  
  // Helper to get human-readable verdict text
  const getVerdictText = (status) => {
    if (!securityReport) return 'Unknown (Exercise caution)';
    
    console.log('Getting verdict for status:', status);
    
    switch(status) {
      case 'malicious':
        return 'Malicious (Not safe to visit)';
      case 'suspicious':
        return 'Suspicious (Exercise caution)';
      case 'safe':
        return 'Genuine (Safe to visit)';
      default:
        const fallbackText = securityReport.is_safe ? 'Genuine (Safe to visit)' : 'Unknown (Exercise caution)';
        console.log('Using fallback verdict text:', fallbackText);
        return fallbackText;
    }
  };
  
  // Helper to get verdict icon
  const getVerdictIcon = (status) => {
    if (!securityReport) return '?';
    
    switch(status) {
      case 'malicious':
        return '⚠️';
      case 'suspicious':
        return '⚠️';
      case 'safe':
        return '✓';
      default:
        return securityReport.is_safe ? '✓' : '?';
    }
  };
  
  return (
    <div className="security-report">
      <div className="report-header">
        <h2>Security Report</h2>
        {onBack && (
          <button className="back-button" onClick={onBack}>
            ← Back to scan
          </button>
        )}
      </div>
      
      <div className="verdict-badge" data-status={securityReport.status || (securityReport.is_safe ? 'safe' : 'unknown')}>
        <div className="verdict-icon">{getVerdictIcon(securityReport.status)}</div>
        <div className="verdict-text">{getVerdictText(securityReport.status)}</div>
      </div>
      
      <div className="report-summary">
        <div className="report-url">
          <h3>Scanned URL</h3>
          <a 
            href={securityReport.url} 
            target="_blank" 
            rel="noopener noreferrer"
            className={!securityReport.is_safe ? 'dangerous-url' : ''}
          >
            {securityReport.url || 'Unknown URL'}
          </a>
        </div>
        
        <div className="report-item score">
          <h3>Security Score</h3>
          <div 
            className="security-score" 
            style={{ color: getSecurityScoreColor(securityReport.security_score) }}
          >
            {Math.round(securityReport.security_score || 0)}/100
          </div>
        </div>
        
        <div className="report-item">
          <h3>Status</h3>
          <div className={`safety-status ${getStatusClass()}`}>
            {securityReport.status || (securityReport.is_safe ? 'Safe' : 'Unsafe')}
          </div>
        </div>
        
        <div className="report-item">
          <h3>HTTPS</h3>
          <div className={`https-status ${securityReport.isHttps ? 'safe' : 'warning'}`}>
            {securityReport.isHttps ? 'Yes' : 'No'}
          </div>
        </div>
        
        <div className="report-item full-width">
          <h3>Risk Assessment</h3>
          <div className="risk-message">
            {securityReport.summary || getPhishingRiskMessage(securityReport)}
          </div>
        </div>
      </div>
      
      {securityReport.error && (
        <div className="report-error">
          <h3>Error During Analysis</h3>
          <p>{securityReport.error}</p>
          {securityReport.errorDetails && (
            <p className="error-details">{securityReport.errorDetails}</p>
          )}
        </div>
      )}
      
      {securityReport.stats && (
        <>
          <button 
            className="toggle-details-btn"
            onClick={() => setShowDetails(!showDetails)}
          >
            {showDetails ? 'Hide Details' : 'Show Details'}
          </button>
          
          {showDetails && (
            <div className="report-details">
              <h3>Detection Statistics</h3>
              <div className="stats-grid">
                <div className="stat-item malicious">
                  <h4>Malicious</h4>
                  <span>{securityReport.stats.malicious}</span>
                </div>
                <div className="stat-item suspicious">
                  <h4>Suspicious</h4>
                  <span>{securityReport.stats.suspicious}</span>
                </div>
                <div className="stat-item harmless">
                  <h4>Harmless</h4>
                  <span>{securityReport.stats.harmless}</span>
                </div>
                <div className="stat-item undetected">
                  <h4>Undetected</h4>
                  <span>{securityReport.stats.undetected}</span>
                </div>
              </div>
              
              {securityReport.details && Object.keys(securityReport.details).length > 0 && (
                <div className="vendor-details">
                  <h3>Security Vendor Results</h3>
                  <div className="vendor-grid">
                    {Object.entries(securityReport.details)
                      .slice(0, 8) // Limit to first 8 vendors to avoid overwhelming the UI
                      .map(([vendor, result]) => (
                        <div 
                          key={vendor} 
                          className={`vendor-item ${result.category || 'undetected'}`}
                        >
                          <h4>{vendor}</h4>
                          <span>{result.result || result.category || 'Unknown'}</span>
                        </div>
                      ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </>
      )}
      
      <div className="report-timestamp">
        <small>Scan completed: {formatDate(securityReport.timestamp)}</small>
      </div>
      
      <div className="report-actions">
        <button className="back-btn" onClick={onBack}>
          Back to Scanner
        </button>
        
        <button className="download-btn" onClick={downloadPDF}>
          Download PDF
        </button>
        
        <button 
          className="email-btn"
          onClick={() => setIsEmailing(true)}
        >
          Email Report
        </button>
      </div>
      
      {securityReport.status !== 'safe' && (
        <div className="help-section">
          <h3>Need Help With This URL?</h3>
          <p>
            {securityReport.status === 'malicious' 
              ? 'This URL has been flagged as potentially malicious. If you believe this is a mistake or need more information, please contact our security team.'
              : 'This URL requires additional scrutiny. If you have questions about its safety or need assistance, our team can help.'}
          </p>
          <div className="contact-info">
            <div className="contact-row">
              <strong>Email:</strong> <a href="mailto:security@secureqrscanner.com">security@secureqrscanner.com</a>
            </div>
            <div className="contact-row">
              <strong>Hotline:</strong> +1 (555) 123-4567
            </div>
            <div className="contact-row">
              <strong>Report URL:</strong> <button 
                className="report-btn"
                onClick={() => {
                  const mailtoUrl = `mailto:security@secureqrscanner.com?subject=URL Report: ${securityReport.status === 'malicious' ? 'Malicious' : 'Suspicious'} URL&body=URL: ${securityReport.url}%0D%0A%0D%0ASecurity Status: ${securityReport.status}%0D%0A%0D%0AAdditional Information:%0D%0A[Please provide any relevant details about this URL]`;
                  window.location.href = mailtoUrl;
                }}
              >
                Report This URL
              </button>
            </div>
          </div>
        </div>
      )}
      
      {isEmailing && (
        <div className="email-overlay">
          <div className="email-form-container">
            <h3>Send Report via Email</h3>
            {emailSent ? (
              <div className="email-success">
                Report sent successfully!
              </div>
            ) : (
              <form onSubmit={handleEmailSubmit}>
                <input
                  type="email"
                  placeholder="Enter email address"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
                <div className="email-form-actions">
                  <button type="submit">Send</button>
                  <button 
                    type="button" 
                    className="cancel-btn"
                    onClick={() => setIsEmailing(false)}
                  >
                    Cancel
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}
      
      {securityReport.is_simulated && (
        <div className="simulation-notice">
          <p><strong>Note:</strong> Using simulated analysis - VirusTotal API unavailable</p>
          <p>For demonstration purposes only. Actual security status may differ.</p>
        </div>
      )}
      
      {securityReport.note && !securityReport.is_simulated && (
        <div className="api-note">
          <p><small>{securityReport.note}</small></p>
        </div>
      )}
    </div>
  );
};

export default SecurityReport; 