import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// Format date to a readable string
export const formatDate = (date) => {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
  }).format(date);
};

// Generate a PDF from the scan report
export const generatePDF = async (reportRef, scanResult, securityStatus) => {
  if (!reportRef.current) return;
  
  try {
    const reportElement = reportRef.current;
    const canvas = await html2canvas(reportElement, {
      scale: 2,
      logging: false,
      useCORS: true,
      allowTaint: true,
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    
    // Generate a filename with today's date
    const dateStr = new Date().toISOString().slice(0, 10);
    const securityLabel = securityStatus || 'scan';
    const filename = `qr-scan-${securityLabel}-${dateStr}.pdf`;
    
    pdf.save(filename);
    return filename;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return null;
  }
};

// Share via email (using mailto)
export const shareViaEmail = (scanResult, securityStatus, securityDetails) => {
  // Truncate long scan results for email
  const maxLength = 500;
  const truncatedResult = scanResult.length > maxLength 
    ? scanResult.substring(0, maxLength) + '...' 
    : scanResult;
  
  // Generate status label for subject
  let statusLabel = '';
  switch (securityStatus) {
    case 'safe':
      statusLabel = '[SAFE]';
      break;
    case 'suspicious':
      statusLabel = '[SUSPICIOUS]';
      break;
    case 'malicious':
      statusLabel = '[MALICIOUS]';
      break;
    default:
      statusLabel = '';
  }
  
  // Compose email body
  const body = `
QR Code Scan Report
-------------------
Date: ${formatDate(new Date())}

Scan Result: 
${truncatedResult}

Security Status: ${securityStatus || 'Unknown'}
${securityDetails ? `Security Details: ${securityDetails}` : ''}

-------------------
Generated by Secure QR Scanner
  `.trim();
  
  try {
    // Prompt for recipient email
    const recipient = prompt('Enter recipient email address:', '');
    
    // If user cancels or doesn't enter an email, return
    if (!recipient || !recipient.trim()) return false;
    
    // Create the mailto URL with recipient
    const subject = `QR Scan Result ${statusLabel}`;
    const mailtoUrl = `mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    
    // Open the mail client
    window.location.href = mailtoUrl;
    
    return true;
  } catch (error) {
    console.error('Error opening email client:', error);
    return false;
  }
}; 